sudo: required
dist: trusty
language: php

php:
  - 7.1

branches:
  only:
    - master 
    - develop


# Build
before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:generate

# Test
script:
  - ./vendor/bin/phpunit

# deploy
after_success: